service: HazeMonitoring

provider:
  name: aws
  runtime: dotnet6
  apiGateway:
    request:
      schemas:
        post-temperature-create:
          name: PostTemperatureCreate
          schema: ${file(api_schema/temperature/post_temperature_create.json)}
  region: sa-east-1

package:
  individually: true
  patterns:
    - '!.idea/**'
    - '!.github/**'

functions:
  temperatureIndex:
    package:
      artifact: bin/release/net6.0/hazeMonitoring.zip
    handler: HazeMonitoring::HazeMonitoring.handlers.TemperatureHandler::Index
    url: true
    events:
      - http:
          path: clusters/{cluster-id}/temperatures
          method: get
          request:
            parameters:
              querystrings:
                total: false
              paths:
                cluster-id: true
  temperatureCreate:
    package:
      artifact: bin/release/net6.0/hazeMonitoring.zip
    handler: HazeMonitoring::HazeMonitoring.handlers.TemperatureHandler::Create
    url: true
    events:
      - http:
          path: clusters/{cluster-id}/temperatures
          method: post
          request:
            parameters:
              paths:
                cluster-id: true
            schemas:
              application/json: post-temperature-create